apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-users
  template:
    metadata:
      labels:
        app: chatbot-users
    spec:
      containers:
        - image: jurebevc/chatbot-users:1.0.0-3.1
          name: chatbot-users
          env:
            - name: DB_PATH
              valueFrom:
                secretKeyRef:
                  name: db-path
                  key: db-path
          ports:
            - containerPort: 8081
              name: server
              protocol: TCP